### ISSUE TITLE
How to change the output of the video to rtmp

### ISSUE THREAD

**Issue by ApacheWang** [Xingtao/FFdynamic#2] opened 2018-12-04 08:36 UTC
Hello, I am a machine learning enthusiast. I just read the project you wrote. It is very good. There are many places worth learning. I want to know how to write the results of onProcess to rtmp. I ran your program and found that the video will be written to disk after about 3 seconds of processing. I want to know how to change it directly to rtmp, in output_url.

**Comment by Xingtao** [comment] 2018-12-04 13:42
which binary program are you running ? If you are running a test, you can change 'Mux' setting. Something like this:
```
    DavWaveOption muxOption((DavWaveClassMux()));
    muxOption.set(DavOptionOutputUrl(), "rtmp://some_rtmp_server/some_stream_id");
```

**Comment by ApacheWang** [comment] 2018-12-05 00:08
Thank you for your answer, I want to run the dynaDnnDetect binary program, I try to use ubuntu camera to receive the video stream, and use yolov3 for onProcess, I want to output the recognition result by rtmp

**Comment by ApacheWang** [comment] 2018-12-05 01:03
Can I directly modify the output_url of the dynaDnnDetect.json file to achieve my goal? I think the reason for the previous failure may be that the recognition speed of the machine does not meet the requirements of the rtmp stream.

**Comment by Xingtao** [comment] 2018-12-05 02:03
Yes, just change settings in 'dynaDnnDetect.json'. for rtmp output, you could change it in line 49.
```
  45   "dyna_detect_global_setting" : {
  46     "max_detectors" : 5,
  47     "max_buf_num_of_detect_streamlet" : 20,
  48     "input_url" : "detect.mov",
  49     "output_url" : "test_dyna_detector.flv"
  50   },
```

For performence, right now each raw frame is processed with detect, which is time consuming. one could skip some frames.  Another way is change opencv's target and backend setting if you have corresponding hardwares

**Comment by ApacheWang** [comment] 2018-12-05 02:30
Ok, thank you very much for your answer.

**Comment by ApacheWang** [comment] 2018-12-06 06:58
Hi, Xingtao, I am sorry to bother you. I would like to ask you a question, how to make dynaDnnDetect skip some frames, I tried to let modules/cvPostDraw not recognize the image, such as commenting out the drawResult function, let it only return 0. But it didn't work. I thought about some time and didn't get a good solution, so I would like to ask you.

**Comment by Xingtao** [comment] 2018-12-06 10:54
hi, just added a detect_interval param for 'cvDnnDetect', you could refer to this commit for details
'''
https://github.com/Xingtao/FFdynamic/commit/1db530f8d775f941e43c92c83c1e7abee7c71aae
'''

**Comment by ApacheWang** [comment] 2018-12-06 11:50
Your answer perfectly solved my problem, thank you big cow！！！

**Comment by ApacheWang** [comment] 2018-12-07 01:22
Hi, Xingtao I want to give you a suggestion. In the interactiveLive module, you can separate the video and audio, because when the audio of multiple streams is merged, you can't get a complete and clear audio.

**Comment by Xingtao** [comment] 2018-12-07 02:14
Proper audio mix post-process is out of my knowledge. Current implementation just add all raw data together (float sample type). This may introduce over/underflow or volume problem.  A simple post-process algorithm may be added later to reduce the noise a little bit.

**Comment by ApacheWang** [comment] 2018-12-07 04:12
Hi, Xingtao, In the interactiveLive module, can I have any way to play video only, that is, separate the video from the audio, and output only the video content, which may be better.

**Comment by ApacheWang** [comment] 2018-12-07 05:41
OK, I found a way, just delete the audio_encode in Conf, but the new problem is, I want to write the result out to the rtmp stream, but directly modifying the output_url of udp does not seem to work, I need to modify other Where?

**Comment by Xingtao** [comment] 2018-12-07 07:14
Hi, just added a new option, allow mute the audio at the beginning, refer to this commit for details

https://github.com/Xingtao/FFdynamic/commit/959f7eed34a3f7f8db8679ce2c149f12c1f85f32

Also, you can keep 'audio_encode' in ialConfig.json,  and then use api to do mute/unmute while program running (/api1/ial/mute_unmute_stream).

**Comment by ApacheWang** [comment] 2018-12-07 07:54
Xingtao, thank you very much, that's great!

**Comment by ApacheWang** [comment] 2018-12-07 08:35
Hi, Xingtao, how do I output the video stream of the interactiveLive module to the rtmp stream, I found that modifying udp_url does not get the correct result.

**Comment by Xingtao** [comment] 2018-12-07 09:31
The InteractiveLive lacks a webUI,  so there is a python script 
 https://github.com/Xingtao/FFdynamic/blob/master/apps/interactiveLive/testScripts/testIal.py
 that can send command to the program.  You could refer this one and set up output url.

**Comment by ApacheWang** [comment] 2018-12-07 10:14
Hi, Xingtao, think you for your answer.Yes, I am modifying it according to this document, as you said. The situation is, I opened the nginx live streaming on my computer, the address is as follows: rtmp://localhost/live. I made changes in the interactiveLive/testScripts/testIal.py file, and changed the fullurl_output_udp_720 to rtmp://localhost/live. I didn't get valid when I used vlc to listen to rtmp://localhost/live. Flow, this is really a place of confusion for me. May I need to change somewhere else?

**Comment by Xingtao** [comment] 2018-12-07 11:42
It should be caused by improper configure in 'ialConfig.json'.    
In this file, there are three output_settings,  720p_200kb, upd_720p, 1080p_400kb, they are output template ids.  

Change 'mpegts'  to  'flv' (rtmp require flv encapsulate) under '720p_200kb'

```
  57       "mux_outputs" : [
  58         {"mux_type" : "ffmpeg", "mux_fmt" : "mpegts", "avdict_mux_option" : {}}
  59       ]
  60     },
``` 

Also, change 'fullurl_output_720' in testIal.py to 'rtmp"//localhost/live' , for  this output in the script will use output setting id '720p_2000kb'.

So, after above modification, you could run the python script, then 
1 -> create room   // will stream rtmp out to your nginx server
2-> add new input // two inputs, will do video mix
3-> other command, like change layout,  etc...

BTW: the whole picture about output is as follow.
In configure file only  output setting template is defined, at run time, we can add many outputs  (different resolution, bitrate,  also many output format,  rtmp, udp, file, hls, etc..), each output use one output setting template.

**Comment by ApacheWang** [comment] 2018-12-07 12:13
Wow, perfect, you successfully solved the problem that bothered me, the original is flv package, I ignored this condition, thank you, Xingtao！！！

**Comment by ApacheWang** [comment] 2018-12-08 13:32
Hi，Xingtao，I have been studying other books these days and have not looked at your project too carefully. I would like to give a little advice on the output multi-screen output style of the interactiveLive module. I found that the video is linearly added and cannot change the display style of multiple videos. For example, there are four screens, one of which takes up most of the video. The other three videos only occupy a small portion. If make the layout diversified, the project will be more perfect.

**Comment by ApacheWang** [comment] 2018-12-08 14:53
Hi, Xingtao, I seem to have found the configuration, is it at apps/appCommon/ial/davWaveSetting.proto?

**Comment by Xingtao** [comment] 2018-12-08 22:55
Yes, that is the place to change layout at runtime via control message. 

Layout is designed with two parts:  predefined layout and specific layout (not implemented).
1. predefined layout 
    Those layouts are fixed,  cell number(input stream number) determines the layout pattern.
    For instance,  two inputs will use 'eHorizonal_2', each cell's coordinate is predefined:
```
 /* file FFdynamic/davImpl/videoMix/cellMixer/layout.cpp */

  77 const map<EDavVideoMixLayout, vector<vector<int>>> CellLayout::s_layoutCoordinates = {
  78     // {0, {}},
  79     {eSingle_1,              {{0},{0},{120},{120}}},
  80     {eHorizonal_2,           {{0,60},{30,30},{60,60},{60,60}}},
  81     {eLeft1SmallRight1Big_2, {{0,24},{0,0},{24,96},{24,120}}},
  82     {eLeft2SmallRight1Big_3, {{0,40,0},{20,20,60},{40,80,40},{40,80,40}}},
  83     {eEqual_4,               {{0,60,0,60},{0,0,60,60},{60,60,60,60},{60,60,60,60}}},
  84     {eLeft1BigRight3Small_4, {{0,80,80,80},{20,0,40,80},{80,40,40,40},{80,40,40,40}}},
```

as shown,  'eHorizonal_2' will use '{{0,60},{30,30},{60,60},{60,60}}}', which means 
```
 * cell1 (x, y, w, h) -> (0,   30, 60, 60)
 * cell2 (x, y, w, h) -> (60, 30, 60, 60)
```
All layouts are in a 120x120 coordinate, with top left (x, y) = (0, 0).
120 is chosen merely because it can divide 2,3,4,5,6, and this covers all cases with a max 36 cells (input streams).

2. specific layout 
    This intends using specific user defined cell coordinates (not implemented yes).
    For instance, take two inputs, user could define each stream's coordinate like this:
    (0,0,80,80) & (42, 36, 50, 50),
    they could have overlap. Also, layer number is supported, indicates Z direction mix order.

So, if you would like to create and use new layout pattern, just modify
```
const map<EDavVideoMixLayout, vector<vector<int>>> CellLayout::s_layoutCoordinates 
```

**Comment by ApacheWang** [comment] 2018-12-08 23:04
Thank you for your detailed answer, it looks very good.

**Comment by ApacheWang** [comment] 2018-12-09 04:00
Hi, Xingtao, I tried to speed up the program with GPU, but it didn't get very good acceleration (my GPU is M40). When I looked at the GPU, I found the reason, the program only used 1% GPU Memory. How to improve the GPU Memory of the application to improve the running efficiency of the program and achieve better acceleration effect?

**Comment by ApacheWang** [comment] 2018-12-09 04:36
My GPU is Nvidia, how can I better use GPU to accelerate dynaDnnDetect module?

**Comment by ApacheWang** [comment] 2018-12-09 04:39
The following is my configuration：
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40           On   | 00000000:00:07.0 Off |                  Off |
| N/A   35C    P0    61W / 250W |    346MiB / 12215MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     18663      C   ./dynaDetector                               105MiB |
|    0     18778      C   ./dynaDetector                               106MiB |
|    0     18867      C   ./dynaDetector                               106MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ApacheWang** [comment] 2018-12-09 05:02
Or replace Mat with UMat.My OpenCV version is 3.4.3 .

**Comment by ApacheWang** [comment] 2018-12-09 09:15
Can I use CUDA to speed up the program? Not opencl .

**Comment by ApacheWang** [comment] 2018-12-09 10:44
Hi, Xingtao, Now I can really use the GPU, but the recognition efficiency is low. It is estimated that it is related to the OpenCL algorithm. Is there any way to speed up?
```
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Tesla M40           On   | 00000000:00:07.0 Off |                  Off |
| N/A   47C    P0   133W / 250W |    410MiB / 12215MiB |     80%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
|    0     32206      C   ./dynaDetector                               399MiB |
+-----------------------------------------------------------------------------+
```

**Comment by ApacheWang** [comment] 2018-12-09 13:25
Hi, Xingtao, I tested the running recognition efficiency of dynaDnnDetect. When detect_interval=5 and only yolov3, the inferTime of M40 is about 850, and the inferTime of P100 is about 630. Can there be any way to make the program run faster?

**Comment by Xingtao** [comment] 2018-12-09 13:42
Hi, with my knowledge, opencv's dnn module cannot use cudnn to accelerate inference. For yolo detector, it may better use darknet(https://github.com/pjreddie/darknet) directly.  Darknet is quite easy to build and interface also quite clean. 
Then the only work is to integrate darknet interface to dynaDetector (namely receive online stream, do video decode and object detect, and finally do rtmp output).
Would you like to write a darknet plugin, similar to cvDnnDetect ? And I can help if you encounter any problem.

**Comment by Xingtao** [comment] 2018-12-09 13:45
> Hi, Xingtao, Now I can really use the GPU, but the recognition efficiency is low. It is estimated that it is related to the OpenCL algorithm. Is there any way to speed up?
> 
> ```
> +-----------------------------------------------------------------------------+
> | NVIDIA-SMI 390.46                 Driver Version: 390.46                    |
> |-------------------------------+----------------------+----------------------+
> | GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
> | Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
> |===============================+======================+======================|
> |   0  Tesla M40           On   | 00000000:00:07.0 Off |                  Off |
> | N/A   47C    P0   133W / 250W |    410MiB / 12215MiB |     80%      Default |
> +-------------------------------+----------------------+----------------------+
>                                                                                
> +-----------------------------------------------------------------------------+
> | Processes:                                                       GPU Memory |
> |  GPU       PID   Type   Process name                             Usage      |
> |=============================================================================|
> |    0     32206      C   ./dynaDetector                               399MiB |
> +-----------------------------------------------------------------------------+
> ```

Use 'nvidia-smi dmon' to see the cuda usage, the 'sm' column stands for actual cuda usage.

**Comment by ApacheWang** [comment] 2018-12-09 14:08
OK, I will have a try 👍 ,thank you.

**Comment by ApacheWang** [comment] 2018-12-09 15:31
Hi, Xingtao, can dynaDnnDetect support cudnn's GPU acceleration? Can I make dynaDnnDetect use cudnn to accelerate inference by modifying the code.

**Comment by ApacheWang** [comment] 2018-12-10 01:54
Hi, Xingtao, I have installed darknet on my computer and it has been used successfully. The problem now is that I want darknet to directly recognize the rtmp/rtsp video stream and output the video stream. What should I do and how to modify the code?

**Comment by Xingtao** [comment] 2018-12-10 02:25
Darknet support cudnn,  so integrate darknet as a plugin, just like cvDnnDetect.cpp, then one can take rtsp input and rtmp output.

**Comment by Xingtao** [comment] 2018-12-10 02:26
I close this issue.  Open another issue related 'darknet' integration if  needed.

**Closed as completed by Xingtao** 2018-12-10 02:26 UTC

**Comment by Generalomosco** [comment] 2020-06-24 16:07
I'm getting same error still "Empty reply from server" with no response!
after starting the service i run the POST request but the http seems not working right! 

`curl -XPOST http://127.0.0.1:8080/api1/ial/create_room -d '{"room_id" : "room1", "input_urls" : ["/home/site.com/webs/web.site.com/public/_stream_in/1.mp4", "/home/site.com/webs/web.site.com/public/_stream_in/2.mp4", "/home/site.com/webs/web.site.com/public/_stream_in/3.mp4"], "room_output_base_url": "/home/site.com/webs/web.site.com/public/_stream_out/", "output_stream_infos" :{"output_setting_id" : "720p_2000kb"} }'`
